export const AUTH_TOKEN = 'TOTAL_EXPERT_NODE/AUTH_TOKEN';
export const CLIENT_ID = 'TOTAL_EXPERT_NODE/CLIENT_ID';
export const CLIENT_SECRET = 'TOTAL_EXPERT_NODE/CLIENT_SECRET';
export const ENVIRONMENT = 'TOTAL_EXPERT_NODE/ENVIRONMENT';
export const ON_AUTHENTICATE = 'TOTAL_EXPERT_NODE/ON_AUTHENTICATE';
export const ON_AUTHENTICATE_FAILURE = 'TOTAL_EXPERT_NODE/ON_AUTHENTICATE_FAILURE';
